import { readFileSync, writeFileSync } from 'fs';

const SCRIPT_MAP = {
    'js/aura/EROS.js': 'sys_eros',
    'js/aura/INTENT.js': 'sys_intent',
    'js/aura/PULSE.js': 'sys_pulse',
    'js/core/aura_lib.js': 'sys_aura',
    'js/core/presets/sys_rpg.js': 'sys_rpg'
};

const data = {};

for (const [filepath, scriptId] of Object.entries(SCRIPT_MAP)) {
    try {
        data[scriptId] = readFileSync(filepath, 'utf8');
        console.log('Read:', filepath);
    } catch (e) {
        data[scriptId] = '// Script not found';
        console.log('Missing:', filepath);
    }
}

const output = `/*
 * Anansi System Data
 * Generated by build_system_data.mjs
 * Do not edit manually.
 */

(function(A) {
    'use strict';
    A.SystemData = ${JSON.stringify(data, null, 2)};
    console.log("Anansi: System Data Loaded (" + Object.keys(A.SystemData).length + " scripts).");
})(window.Anansi);
`;

writeFileSync('js/core/system_data.js', output);
console.log('Wrote: js/core/system_data.js');
